### ISSUE TITLE
 Failed to write to image store: [POST /storage/{store_name}][500] WriteImage default &{Code:0xc420ab6da0 Message:Invalid configuration for device '0'.}.

### ISSUE THREAD

**Issue by fdawg4l** [vmware/vic#3528]
Via SM on Socialcast

```I'm running ViC (GA Version) in my lab, and it worked fine a couple of days. Suddenly all "Docker run" failed with :
docker: Failed to write to image store: [POST /storage/{store_name}][500] WriteImage default &{Code:0xc420ab6da0 Message:Invalid configuration for device '0'.}.

When deploying new VCH's i get the same problem. Tried different datastores/folders with the --image-store command with no luck. It creates the ViC folder and the following structure:
TemplatesNFS01/Containers
VIC

UID

Images

scratch

imageMetadata
Running this command:
vic-machine-linux create --target vcenter1.local.steffenmoen.no --user Administrator@vsphere.local --password ****** --bridge-network ViCPrivate_pg --public-network ViCPublic_pg --name VCH15 --image-store TemplatesNFS01/Containers --compute-resource CNA --dns-server=192.168.2.30 --client-network ViCPublic_pg --force --no-tlsverify' using encoding 'Default System Encoding'
```

**Comment by steffenmoen** [comment]
[All.log.zip](https://github.com/vmware/vic/files/658774/All.log.zip)
Attached log bundle with container logs.

**Comment by fdawg4l** [comment]
Hi @steffenmoen, thanks for the log.  However, it looks like this isn't the log bundle I was referring to.  Apologies, I should've been more clear.  

You can get a VIC log bundle by going to the admin URL (which is printed after running `vic-machine` to install VIC, usually something like `https://10.118.67.226:2378/`), logging in, and clicking `Log Bundle` on the right.  A `.zip` file will be downloaded.  Please attach that file here. 

NOTE: All sensitive info (like passwords) are scrubbed from the log so it should be safe to post here.

**Comment by steffenmoen** [comment]
[logs.zip](https://github.com/vmware/vic/files/683216/logs.zip)
Sorry, i don't know what happened to the log bundle. Please try this one.

**Comment by fdawg4l** [comment]
Thanks for the logs!

```
116 time=2016-12-16T09:01:41.883389028Z level=debug msg=op=252.4 (delta:41.614288979s): Scratch disk created with size 8000000

130 time="2016-12-16T09:01:45Z" level=debug msg="Index: inserting http://VCH13/storage/images/422fce56-5b54-e347-c93b-f122ad8a2ae5/scratch (parent: http://VCH13/storage/images/422fce56-5b54-e347-c93b-f122ad8a2ae5/scratch) in index"·  
``

We create scratch, then we can't find it.

```
157 time=2016-12-16T09:02:36.712851192Z level=debug msg=[BEGIN] [github.com/vmware/vic/pkg/vsphere/disk.(*Manager).CreateAndAttach:85] [vmNFS03] Images/VIC/422fce56-5b54-e347-c93b-f122ad8a2ae5/images/511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158/511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158.vmdk·                                                                                          
158 time=2016-12-16T09:02:36.712877118Z level=info msg=op=252.8 (delta:1.110932103s): Create/attach vmdk [vmNFS03] Images/VIC/422fce56-5b54-e347-c93b-f122ad8a2ae5/images/511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158/511136ea3c5a64f264b78b5433614aec563103b4d4702f3ba7d4d2698e22c158.vmdk from parent [vmNFS03] Images/VIC/422fce56-5b54-e347-c93b-f122ad8a2ae5/images/scratch/scratch.vmdk·                      159 time=2016-12-16T09:02:36.744725750Z level=debug msg=op=252.8 (delta:1.142768605s): Attach reconfigure task=Task:task-14213·                                                                                                                                                                                                                                                                                                          160 time="2016-12-16T09:02:36Z" level=debug msg="unexpected fault on task retry : &types.InvalidDeviceSpec{InvalidVmConfig:types.InvalidVmConfig{VmConfigFault:types.VmConfigFault{VimFault:types.VimFault{MethodFault:types.MethodFault{FaultCause:(*types.LocalizedMethodFault)(nil), FaultMessage:[]types.LocalizableMessage(nil)}}}, Property:\"deviceChange[0].device.backing.fileName\"}, DeviceIndex:0}"·   
```

**Comment by fdawg4l** [comment]
@steffenmoen Can you give us some details about the datastore?  Is it a storage appliance or a software NAS?

Also the `vic-machine` command pasted in the first comment mentions `TemplatesNFS01` but the datastore mentioned in the logbundle is `vmNFS03`.  I just want to verify we're looking at the right logs.

**Comment by steffenmoen** [comment]
@fdawg4l 
This is a nested ESXi environment with two nodes. Both connected to shared NFS datastore (Synology NAS for home use) I have deployed several VCH's and tried both TemplatesNFS01 and vmNFS03.
So for the logs uploaded vmNFS03 is the correct one.

The first VCH I deployed worked a couple of days, but suddenly started to get this error.
When deploying new VCH's they fail immediately.

Kind regards,
Steffen

**Comment by fdawg4l** [comment]
> This is a nested ESXi environment with two nodes

@steffenmoen from a vsphere perspective, that's not a supported installation.  But, we develop on a similar setup (minus the synology NAS) so I'm not sure where the issue is just yet.

Do you know what filesystem the synology NAS is formatted with?  I'm reading synology makes NASes which run all manner of filesystems (Ext, btrfs, ntfs, etc) and want to narrow down our scope.

Also, have you tried your setup with iSCSI?  This should avoid any filesystem issues the synology may introduce since the iSCSI LUN bypasses whatever filesystem the underlying data is stored with.  We've had goo experiences with a user who did the same.  You might want to give that a go while we try to figure out where things aren't happy.

Lastly, (before trying iscsi) can you try installing a VCH once more, grab a new bundle, and include the `hostd.log` and email it to me at ahmedf at vmware dot com?

**Comment by steffenmoen** [comment]
@fdawg4l Sorry for the late reply, but I have been struggling with the iSCSI setup.
I think that the Synology NAS (DS415+) is using Btrfs file system, but I get the same error when trying a iSCSI LUN from this NAS as well.
I will grab a fresh logbundle and send it by mail.

**Comment by fdawg4l** [comment]
Hi @steffenmoen,

Apologies for the delay!  I wanted to confirm you were still seeing the issue reported here.  If so, could you grab the latest bits and try the install once more?  We've made changes to the code and I want to make sure you're up to date before going further.

Thanks!

**Comment by steffenmoen** [comment]
Hi,

I am on vacation at the moment, but will download the latest build and test when I get back.

Kind regards,

Steffen Moen
Sendt fra min iPhone

Den 22. feb. 2017 kl. 07.20 skrev Faiyaz Ahmed <notifications@github.com<mailto:notifications@github.com>>:


Hi @steffenmoen<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_steffenmoen&d=DwMFaQ&c=uilaK90D4TOVoH58JNXRgQ&r=-OS9SsFEzNFgvz1qf6vhPA&m=mGU5ceRQTkG447ORAqOaQ0V4doVfIvndCgwWqMld94s&s=6yJt1LE5wkBt9bFGlBQmA88KhuPVScALCoV1y-93sEI&e=>,

Apologies for the delay! I wanted to confirm you were still seeing the issue reported here. If so, could you grab the latest bits and try the install once more? We've made changes to the code and I want to make sure you're up to date before going further.

Thanks!

**Comment by fdawg4l** [comment]
Thanks Steffen!

**Comment by stuclem** [comment]
Attempted write-up for the 0.9 release notes:

----

- <b>VCH deployment fails with failure to write to image store. [#3528](https://github.com/vmware/vic/issues/3528)</b><br> When you deploy a VCH, the deployment fails with the following error:<pre>docker: Failed to write to image store: 
[POST /storage/{store_name}][500] WriteImage default &
{Code:0xc420ab6da0 Message:Invalid configuration for device '0'.}</pre>

----

This is not very informative. @fdawg4l can you please provide a couple of lines to summarize the issue? Thanks!

**Comment by stuclem** [comment]
Per Slack chat with @fdawg4l, this probably doesn't need to be documented in the RNs. Removed from RNs and removing the kind/note tag.

**Comment by mdubya66** [comment]
Closing as not reproducible. Please reopen if seen again.
