### ISSUE TITLE
vic-machine delete can result in non-containerVMs being deleted

### ISSUE THREAD

**Issue by cgtexmex** [vmware/vic#6603]
The vic-machine delete command is responsible for removing a VCH appliance and it's containerVMs.  The following issues have been identified:

- a VM is determined to be a containerVM if it resides in the appliance's resource pool and does not have extraConfig that would identify it as a VCH appliance.  PoweredOff VMs are deleted by default and if `--force` is supplied to the `vic-machine delete` then both poweredOn and poweredOff VMs are deleted.  This results in the deletion of any non-containerVMs that happen to reside in the appliance resource pool.
- If another VCH appliance is in the target VCH appliance resource pool then any disks attached to it will be detached.  This would cause problems for the non-target VCH appliance when there is a docker pull, commit, cp or diff operation in process.  

To address these issues the following changes need to be made:
- [ ] vic-machine delete will fail if the target resource pool is the default resource pool of the cluster -- an appliance should never be able to be deployed to the default rp of the cluster, but this will be an added measure of safety.
- [x] A VM will only be deleted if it's determined to be a containerVM.  This determination will be made by resource pool residence AND interrogation of the VM extraConfig for containerVM entries.  This will prevent non-containerVMs from being deleted.
- [x] A VCH appliance will only be acted on (detaching disks) if it's the target VCH.  If another VCH resides in the target resource pool it will be untouched.  That determination will be made by the vSphere moRef and the VM extraConfig.

**Comment by cgtexmex** [comment]
@pdaigle @mlh78750 @corrieb @mdubya66 please review the steps that are going to be taken to resolve this issue.  I discussed the change with @hickeng and it was agreed upon that we would not introduce a tight coupling between VCH appliance and containerVMs.  This means that if a containerVM resides in the target resource pool it will be deleted -- regardless of which VCH created said containerVM.  That scenario _should_ only arise when a containerVM has been manually moved from one resource pool to another.  I am going to investigate the possibility of limiting those moves, but that might not make it into this change.

When this issue was discovered there was discussion on providing more granular `--force` options -- (i.e. `--delete-volumes`, `--ignore-thumbprint`, etc) -- those will be addressed in another issue that @matthewavery is creating, socializing and assigning to the `LifeCycle` team.

**Comment by mlh78750** [comment]
@cgtexmex Do we allow multiple VCH installed on a single RP? If we do, then the do need to check to see if the cVM parent == the VCH being deleted.

**Comment by cgtexmex** [comment]
@mlh78750 by default we don't allow it.  Which means if you deploy an appliance the RP and Appliance name are the same.  If you attempt to deploy a second appliance to the same RP then the vSphere call (CreateVM_Task) will fail.  

BUT..If you manually rename the first appliance prior to deploying the second...then it will succeed..resulting in two appliances in one RP.  I think a rename is a valid operation by a VI Admin and shouldn't be disallowed (i.e. disabling the method).

If we are intent on not coupling the appliance to the containerVMs then there are probably a few options to safe guard, but most likely the easiest would be to check for any existing appliances in the target RP and fail.

**Comment by cgtexmex** [comment]
@andrewtchin here's the issue I mentioned via slack.  There's also bugzilla (1983020) which has the specific steps to recreation.  

In this particular instance the customer had deployed vic 1.2 which had a bug around resource pool creation.  The initial rp failed to create but since the `--force` flag was used to install the vic appliance was created in the parent resource pool.   When the customer deleted the install they used `--force` flag so that powerOn & poweredOff vms are removed...unfortunately it removed all VMs in the resource pool and not just the containerVMs.

As of 1.2.1 the create RP issue and subsequent creation in the parent RP have been fixed.  The issues that remain are outlined in the initial issue.

**Comment by andrewtchin** [comment]
Currently `vic-machine delete` with `--id` and `--force` specified is unable to delete a VCH that has been moved out of its RP and its RP deleted because `vic-machine` bails when it can't find the RP. I propose that in this case, if `--force` is specified`, we assume any child cVMs are gone because the RP is gone and that we continue to delete the VCH and its associated resources like images, volume stores, and networks (all the steps in `DeleteVCH` before deleting the VCH itself. 
https://github.com/vmware/vic/blob/master/lib/install/management/delete.go#L34

**Comment by mlh78750** [comment]
I'd like for us to address this properly when we address #3118.

**Comment by hickeng** [comment]
@andrewtchin This does not address the case that was actually observed where the VCH was deployed into the root of a cluster. In that scenario the cluster still exists.

We create cVMs with a defined configuration, part of which is used for the version check. We can ensure that we only delete VMs that have a version key and are therefore identified as cVM. Alternative would be the guest OS identifier.

Given we are not tolerant to a VCH (or containerVM) being moved out of the resource pool they're originally created in we could look at disabling moving both the endpoint and the containerVMs using `AuthorizationManager` as we do for VM->Delete

**Comment by andrewtchin** [comment]
@hickeng My comment was only referring to one of the points required to be addressed for this issue - to your point I did add a check that a VM is actually a containerVM before vic-machine deletes it
